create database rp;
use rp;

-- 1----
CREATE TABLE STUDENT(STUDENT_ID INT  PRIMARY KEY,
					EMAIL VARCHAR(50) UNIQUE,
                    NAME VARCHAR(49) NOT NULL);
	ALTER TABLE STUDENT ADD COLUMN  AGE INT;
    ALTER TABLE STUDENT ADD COLUMN  GENDER VARCHAR(78);
SELECT * FROM STUDENT;
    
-- 2  --- 
CREATE TABLE COURSES  (COURSE_ID INT PRIMARY KEY,
				COURSE_NAME VARCHAR(78) NOT NULL);
ALTER  TABLE COURSES ADD COLUMN DURATION INT;
                     
-- 3-- 
CREATE TABLE clg(CLG_ID INT PRIMARY KEY, 
          CLG_NAME VARCHAR(67) NOT NULL);
ALTER TABLE CLG ADD COLUMN CITY VARCHAR(78);
          
-- 4--
CREATE TABLE MARK(MARK_ID INT PRIMARY KEY,
               MARKS INT,
            SUBJECT_N  VARCHAR(89),
            SDENT_ID INT,
            FOREIGN KEY (SDENT_ID) REFERENCES STUDENT(STUDENT_ID),
            CHECK (MARKS>=0));
SELECT *FROM MARK;
            
-- 5 --
CREATE TABLE TEACHER(TEACH_ID INT PRIMARY KEY,
               TEACH_NAME VARCHAR(89) NOT NULL,
               DEPT VARCHAR(89));
               
-- 6--
CREATE TABLE SUB( SUB_ID INT PRIMARY KEY,
                 SUB_NAME VARCHAR(89) NOT NULL,
                 TEACHER_ID INT,
		foreign key(TEACHER_ID) references TEACHER(TEACH_ID));
                 
                 
-- 7==
CREATE TABLE CLASS(ROOM_ID INT PRIMARY KEY,
                   ROOM_NAME VARCHAR(89),
                   CAPACITY INT,CHECK (CAPACITY>0));
                   
-- 8--
CREATE TABLE ATTEND(ATTEND_ID INT PRIMARY KEY,
                    STUDENT_ID INT,
                    ATTEND DATE,
                    STTUS VARCHAR(89),
		foreign key (STUDENT_ID)  references STUDENT(STUDENT_ID),
        CHECK (STTUS IN('PRESENT','ABSENT')));
DROP TABLE ATTEND;

-- 9--
CREATE TABLE FEES(FEE_ID INT PRIMARY KEY,
                  STUDENT_ID INT ,
                  AMOUNT INT,
                  PAYMENT_DATE DATE,
                  foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),
                  CHECK(AMOUNT>0));

-- 10===
CREATE TABLE LIB(BOOK_ID INT PRIMARY KEY,
				BOOK_NAME VARCHAR(89),
                AUTHOR VARCHAR(89),
                PRICE INT,
                CHECK(PRICE>0));
                
                
 -- BIUSNESS TABLE---
 -- 11
 CREATE TABLE CUSTOMERS(CUST_ID INT PRIMARY KEY, EMAIL VARCHAR(89) UNIQUE);
 CREATE TABLE ORDERS(ORDER_ID INT PRIMARY KEY,CUSTOMER_ID INT,foreign key(CUSTOMER_ID) references CUSTOMERS(CUST_ID));
 CREATE TABLE PRODUCT( PRODUCT_ID INT PRIMARY KEY,PRICE INT, CHECK(PRICE>0));
 CREATE TABLE SUPPLIER(SUPPLIER_ID INT PRIMARY KEY);
 CREATE TABLE PURCHASE(PURCHASE_ID INT PRIMARY KEY, SUPP_ID INT,foreign key(SUPP_ID) references SUPPLIER(SUPPLIER_ID));
 CREATE TABLE EMPLOYEE(EMP_ID INT PRIMARY KEY, SALARY INT, CHECK(SALARY>0));
 CREATE TABLE SALARY(SALARY_ID INT PRIMARY KEY, EMPP_ID INT,foreign key(EMPP_ID) references EMPLOYEE(EMP_ID));
 CREATE TABLE SALE(SALE_ID INT PRIMARY KEY,PRO_ID INT, foreign key(PRO_ID) references PRODUCT(PRODUCT_ID));
 CREATE TABLE INVOICE(INVOICE_ID INT PRIMARY KEY, CUSTM_ID INT, foreign key(CUSTM_ID) references CUSTOMERS(CUST_ID));
 CREATE TABLE PAYMENT(PAY_ID INT PRIMARY KEY, INVOICE_ID INT,foreign key(INVOICE_ID) references INVOICE(INVOICE_ID));
 
                
                