-- CONSTRAINTS

#1 . NOT NULL
CREATE TABLE T1(ID INT NOT NULL,FIRSTNAME VARCHAR(20),Age INT);
DESC T1;

INSERT INTO T1 VALUES(1,'RUPESH',22);
SELECT * FROM T1;
INSERT INTO T1 VALUES(2,NULL,23);
INSERT INTO T1 VALUES(3,'MOHIT',5); -- GIVES ERROR DUE TO NOT NULL CONSTRAINT


# 2 .CHECK CONSTAINT-------->
CREATE TABLE T2(ID INT NOT NULL,Fname VARCHAR(40),Age INT,

CHECK(AGE>=18));


INSERT INTO T2 VALUES(1,'RUPESH',22);
SELECT * FROM T2;
INSERT INTO T2 VALUES(2,'KARTIK',23);
INSERT INTO T2 VALUES(3,'MOHIT',5); 

# 3 .DEFAULT CONSTIANT----->

CREATE TABLE T3(orderid INT NOT NULL,
Products VARCHAR(20),Amount INT,
Returned VARCHAR(10) DEFAULT "NO");

DESC T3;

INSERT INTO T3 VALUES(1,'shirt',455);  -- gives an error
INSERT INTO T3(ORDERID ,PRODUCTS,AMOUNT) VALUES (1,'shirt',455);
SELECT * FROM T3;

INSERT INTO T3 VALUES (2,'JEANS',1400,'YES');

#4 .ENUM(Not a constraint rather this is a DATA TYPE IN MYSOL)

CREATE TABLE T4(ID INT NOT NULL,Fname VARCHAR(20),
Gender ENUM('Male','Female'));

desc t4;

INSERT INTO T4 VALUES(1,'KARTIKA','FEMALE');
INSERT INTO T4 VALUES(2,'MOHIT','MALE'); 
INSERT INTO T4 VALUES(2,'MOHIT','XYZ'); 
select*from t4;


#---------------------------------------------------------


-- KEY CONSTRAINTS
#5. UNIQUE KEY
CREATE TABLE T5 (ID INT UNIQUE,AGE INT);
DESC T5;

INSERT INTO T5 VALUES(1,25);
INSERT INTO T5 VALUES(2,24);
INSERT INTO T5 VALUES(NULL,33);
SELECT *FROM T5;

# PRIMARY KEY

-- Combination of NOT NULL+ UNIQUE CONSTAINT IN TABLE--

CREATE TABLE T6( ID INT PRIMARY KEY,AGE INT);
DESC T6;

INSERT INTO T6 VALUES(1,24);
INSERT INTO T5 VALUES(NULL,33);
INSERT INTO T6 VALUES(1,24);
SELECT *FROM T6;

CREATE TABLE T8( ORDERID INT PRIMARY  KEY, 
PRODUCT VARCHAR(50) NOT NULL,
AMT INT,SIZE ENUM('SMALL','MEDIUM','LARGE'),
CITY VARCHAR(50),RATING INT ,
REVIEW VARCHAR(60)DEFAULT "YES",
CHECK(AMT>=1200));
DESC T8;
INSERT INTO T8 VALUES(1,'BOTTLE',34000,'SMALL','PUNE',4,"YES");

SELECT *FROM T8;



#Auto increment (function)(primary key)
CREATE TABLE studs(ID INT PRIMARY KEY auto_increment,Fname VARCHAR(50),AGE INT);

INSERT INTO STUDS(FNAME,AGE) VALUES('RUPESH',22),('MOHIT',23),('AKSHAY',21);

SELECT *FROM STUDS;


#parent table
CREATE TABLE C (ID INT PRIMARY KEY,C_NAME VARCHAR(20),FEES INT);

INSERT INTO C VALUES(10,'DS',500),(20,'DA',300),(30,'GENAI',700);

SELECT *FROM C;


# CHILD TABLE

CREATE TABLE S ( S_IN INT PRIMARY KEY,SNAME  VARCHAR(20),COURSE_TAKEN INT,
foreign key(COURSE_TAKEN) references C(ID));

DESC S;


INSERT INTO S VALUES(1,'AMIT',10),(2,'RUPESH',20),(3,'MOHIT',30),(4,'AKSHAY',30);

SELECT * FROM S;


SELECT * FROM C;
SELECT * FROM S;


#---------------------------------------------------------------------------
# on cascade

CREATE TABLE COURSE (ID INT PRIMARY KEY,C_NAME VARCHAR(20),FEES INT);
INSERT INTO COURSE VALUES(10,'DS',500),(20,'DA',300),(30,'GENAI',700);

SELECT *FROM COURSE;

CREATE TABLE SDT ( S_IN INT PRIMARY KEY,SNAME  VARCHAR(20),COURSE_TAKEN INT,
foreign key(COURSE_TAKEN) references COURSE(ID)
on DELETE CASCADE
ON UPDATE CASCADE DESC SDT;
INSERT INTO SDT VALUES(1,'AMIT',10),(2,'RUPESH',20),(3,'MOHIT',30),(4,'AKSHAY',30);
SELECT * FROM SDT;



DELETE FROM COURSE WHERE ID = 10;
UPDATE COURSE SET ID = 100 WHERE ID = 20;

SELECT * FROM COURSE;
SELECT * FROM SDT;



#EXMAPLE

CREATE TABLE CUSTOMER(C_ID INT PRIMARY KEY, CNAME VARCHAR(50) NOT NULL, EMAIL_ID  VARCHAR(70),
ADDRESS VARCHAR(48));

INSERT INTO CUSTOMER (C_ID, CNAME, EMAIL_ID, ADDRESS)
VALUES
(1, 'Rupesh Patil', 'rupesh@gmail.com', 'Pune'),
(2, 'Amit Sharma', 'amit.sharma@gmail.com', 'Mumbai'),
(3, 'Sneha Joshi', 'sneha.joshi@gmail.com', 'Nashik'),
(4, 'Rahul Deshmukh', 'rahul.deshmukh@gmail.com', 'Nagpur'),
(5, 'Priya Kulkarni', 'priya.kulkarni@gmail.com', 'Jalgaon');


SELECT *FROM CUSTOMER;


CREATE TABLE ORDERS(ORD_ID INT PRIMARY KEY,AMT INT, MODE_P varchar(40), COUSTMER_ID INT,
foreign key (COUSTMER_ID) references CUSTOMER(C_ID));


INSERT INTO ORDERS (ORD_ID, AMT, MODE_P, COUSTMER_ID)
VALUES
(101, 2500, 'UPI', 1),
(102, 1800, 'Cash', 2),
(103, 3200, 'Credit Card', 3),
(104, 1500, 'Debit Card', 4),
(105, 4500, 'UPI', 5);

SELECT * FROM ORDERS;