#1.  NOW  function ---->  current date and time

SELECT NOW();
SELECT CURTIME();
SELECT CURDATE();

SELECT DATE('2026-09-29 14:19:02');
SELECT DATE(NOW());

SELECT DATEDIFF(CURDATE(),'2000-09-25');

SELECT DATE_ADD(CURDATE(),INTERVAL 5 DAY);
SELECT DATE_FORMAT('2026-09-25','%d/%m/%y');
SELECT DATE_FORMAT('2026-09-25','%D/%M/%Y');


SELECT DAY(CURDATE());
SELECT MONTH(CURDATE());
SELECT YEAR(CURDATE());
SELECT DAYNAME(CURDATE());
SELECT MONTHNAME(CURDATE());


#DATE ANALYSIS ON ORDER TABLE.
SELECT * FROM ORDERS;
DESC ORDERS;

ALTER TABLE  ORDERS MODIFY COLUMN  ORDER_DATE DATE,
                    MODIFY COLUMN  ORDER_DATETIME DATETIME;

DESC ORDERS;

SELECT * FROM ORDERS;
ALTER TABLE ORDERS MODIFY COLUMN DELIVERY_DATE_TEXT DATE;

SELECT DELIVERY_DATE_TEXT,
STR_TO_DATE(DELIVERY_DATE_TEXT,'%d-%m-%Y')  FROM ORDERS;

#CREATE A NEW COLUMNS
ALTER TABLE ORDERS ADD COLUMN DELIVERY_DATE  DATE;

SELECT STR_TO_DATE(DELIVERY_DATE_TEXT,'%d-%m-%Y') FROM ORDERS;

SET SQL_SAFE_UPDATES= 0;

UPDATE ORDERS SET DELIVERY_DATE = STR_TO_DATE(DELIVERY_DATE_TEXT,'%d-%m-%Y');

SELECT * FROM ORDERS;
DESC ORDERS;

SELECT DATE(ORDER_DATETIME) FROM ORDERS;
SELECT DATE_ADD(DELIVERY_DATE,INTERVAL 2 DAY) FROM ORDERS;


# FIND OUT AVERAGE DELIVERY DAY FOR EACH CITY

   ALTER TABLE ORDERS ADD COLUMN DELIVERY_DAYS INT;

   UPDATE ORDERS SET DELIVERY_DAYS = DATEDIFF(DELIVERY_DATE,ORDER_DATE);
   SELECT CITY,AVG(DELIVERY_DAYS) FROM ORDERS GROUP BY CITY;
   
#AVERAGE  PRICE FOR EACH MONTH WITHOUT CREATING KMONTH COLUMN
  SELECT MONTHNAME(order_date),AVG(price) 
  FROM orders GROUP BY MONTHNAME(order_date);

