
--  WINDOW FUNCTION-----------------

SELECT * FROM SALES;
SELECT AVG(SALES_AMOUNT) FROM SALES;

SELECT *,AVG(SALES_AMOUNT) FROM SALES;  # GIVE AN ERROR.
#

# 0VER()---
SELECT * , AVG(SALES_AMOUNT) OVER() AS AVERAGE FROM SALES;


# USED   (PARTITION BY)  IN WINDOW FUCTION  
-- WORKS SIMILAR TO GROUP BY
-- USED IN WINDOW FUNCTION
-- DIVIDES AND THEN RETURN THE AG VALUES BASED ON EACH GROUPED VALUES
SELECT * , AVG(SALES_AMOUNT) OVER(PARTITION BY REGION) AS AVERAGE FROM SALES ;



-- FIND MIN,MAX,SUM AVG OF SALES AMOUNT FRO EACH DEPT
SELECT * , MIN(SALES_AMOUNT) OVER(PARTITION BY DEPARTMENT) AS MIN_SALES, 
MAX(SALES_AMOUNT) OVER(PARTITION BY DEPARTMENT) AS _MAX ,
SUM(SALES_AMOUNT) OVER(PARTITION BY DEPARTMENT) AS SUM_ ,
AVG(SALES_AMOUNT) OVER(PARTITION BY DEPARTMENT) AS AVG_ FROM SALES ;


-- FIND MIN SALES DONE BY EACH EMPLOYES
SELECT * , MIN(SALES_AMOUNT) OVER(PARTITION BY EMP_ID) AS MIN_SALES FROM SALES ;

-- FIND MAX SLAES DONE BY EACH DEPARTMENT
SELECT * , MAX(SALES_AMOUNT) OVER(PARTITION BY DEPARTMENT) AS MAX_SALE FROM SALES ;

-- COMMON TABLE EXPRESSION

